vm_types:
- name: medium
  cloud_properties: {}
- name: medium-compute-tier
  cloud_properties: {}

azs:
- name: z1
  cloud_properties: {}
- name: z2
  cloud_properties: {}

disk_types:
- name: default
  disk_size: 10000
  cloud_properties: {}
- name: 10K-disk
  disk_size: 100000
  cloud_properties: {}
- name: 100K-disk
  disk_size: 1000000
  cloud_properties: {}

networks:
- name: service
  subnets:
  - az: z1
    cloud_properties:
      name: random
    range: 10.244.9.0/28
    reserved:
    - 10.244.9.1

compilation:
  cloud_properties:
    name: random
  network: service
  az: z1
  reuse_compilation_vms: true
  workers: 5

