---
name: {{product['short_name']}}-on-demand-broker

director_uuid: <%= `bosh target > /dev/null 2>&1 && bosh status --uuid` %>

cf: &cf-config
  url: https://api.local2.pcfdev.io
  root_ca_cert: #<root ca cert for CF> # optional
  authentication:
    url: https://uaa.local2.pcfdev.io
    user_credentials: # can use client_credentials instead
      username: user
      password: pass
    client_credentials: # can use client_credentials instead
      client_id:
      secret:

bosh: &bosh-config
  url: https://192.168.50.4:25555
  root_ca_cert: #<root ca cert for CF> # optional
  authentication:
    basic: # can use uaa instead
      username: admin
      password: admin
    uaa: # or go with basic auth
      url:
      client_id:
      client_secret:

cf_properties: &cf-properties
  apps_domain: local2.pcfdev.io
  nats:
    #host: 10.244.0.6
    host: 10.0.2.15
    port: 4222
    username: nats
    password: nats


releases:
  - name: &odb-broker-release on-demand-service-broker
    version: 0.12
  - name: &service-adapter-release {{product['short_name']}}-service-adapter-release
    version: latest
  {% for managed_service_release in context['managed_service_releases'] %}
  - name: {{managed_service_release['name']}}
    version: {{managed_service_release['version']}}
  {% endfor %}

stemcells:
  - alias: trusty
    os: ubuntu-trusty
    version: latest

instance_groups:
  - name: broker
    instances: 1
    jobs:
      - name: broker
        release: *odb-broker-release
        properties:
          port: &broker_port 8080
          username: testuser
          password: testuser
          disable_ssl_cert_verification: true
          cf: *cf-config
          bosh: *bosh-config
          service_adapter:
            path: /var/vcap/packages/odb-service-adapter/bin/service-adapter
          service_deployment:
            releases:
              {% for managed_service_release in context['managed_services_releases'] %}
 
              - name: {{managed_service_release['name']}}
                version: {{managed_service_release['version']}}
                jobs: {{ managed_service_release['jobs'] }}
              {% endfor %}  
            stemcell:
              os: ubuntu-trusty
              version: latest
          service_catalog:
            id: {{ service['id']}}
            service_name: {{product['short_name']}}-on-demand
            service_description: {{product['description']}}
            bindable: true
            plan_updatable: true
            tags: [{{ product['short_name'] }}]
            plans:
            {% for plan in service['service_plans'] %}
              - name: {{ plan['name']}}
                plan_id: {{ plan['id']}}
                description: {{ plan['description']}}
                instance_groups:
                {% for vm in plan['vms'] %}
                - name: {{ vm['name'] }}
                  vm_type: medium
                  instances: {{ vm['instances'] }}
                  azs: [ "z1" ]
                  persistent_disk: *small-disk
                  networks: ["service"]
                properties:
                  cf: *cf-properties
                  jobType1:
                    listen_port: 8080
                    address: jobType1-small
                    username: admin
                    password: admin
                    memory:
                      max_heap: 1024
                      min_heap: 1024
                  jobType2:
                    listen_port: 8080
                    address: jobType2-small
                    username: admin
                    password: admin
                    memory:
                      max_heap: 1024
                      min_heap: 1024
                    {% endfor %}
                  
              {% endfor %}

      - name: {{ product['name'] }}
        release: *service-adapter-release

    vm_type: medium
    stemcell: trusty
    azs: [ "z1" ]
    networks:
      - name: service

  - name: register-broker
    lifecycle: errand
    instances: 1
    jobs:
      - name: register-broker
        release: *odb-broker-release
        properties:
          broker_name: {{product['short_name']}}
          disable_ssl_cert_verification: true
          cf: &cf
            api_url: https://api.local2.pcfdev.io
            admin_username: admin
            admin_password: admin
    vm_type: medium
    stemcell: trusty
    networks: [{name: service}]
    azs: [ "z1" ]

update:
  canaries: 1
  canary_watch_time: 3000-180000
  update_watch_time: 3000-180000
  max_in_flight: 4
